spoothy-bucket-name       = "spoorthy-us-east-1-rnd"
spoothy-bucket-tag_name   = "spoorty_RND"
spoothy-bucket-tag_env    = "Sandbox"
ami_id                    = "ami-03c7d01cf4dedc891"
instance_type             = "t3.micro"