spoothy_bucket_name       = "spoorthy-us-east-1-rnd"
spoothy_bucket_tag_name   = "spoorty_RND"
spoothy_bucket_tag_env    = "Sandbox"
# ami_id                    = "amzn2-ami-hvm-*-x86_64-ebs"
# instance_type             = "t3.micro"